### ISSUE TITLE
local variable 'dm' referenced before assignment

### ISSUE THREAD

**Issue by sipvoip** [evilpete/insteonrf#2]
[root@marge insteonrf]# ./rf_reciv.py | ./print_pkt.py
bandwidth  187500.0
0B : B0 C5 3B : 72 DC 25 : 19 00 67              crc 67
07 : B0 C5 3B : 72 DC 25 : 19 00 2B              crc 2B
03 : B0 C5 3B : 72 DC 25 : 19 00 EF              crc EF
2B : 72 DC 25 : B0 C5 : 
Extract Failed :
    local variable 'dm' referenced before assignment
Traceback (most recent call last):
  File "./print_pkt.py", line 59, in <module>
    j = print_insteon_pkt(line, verb=opt_verbose)
  File "/root/insteon/insteonrf/insteonrf/parse_rf.py", line 220, in print_insteon_pkt
    pktlist = get_pkt(dat, timestp)
  File "/root/insteon/insteonrf/insteonrf/parse_rf.py", line 120, in get_pkt
    pkt =  Pkt( dat[sb[0]:sb[1]], ts, sb[0]) 
  File "/root/insteon/insteonrf/insteonrf/parse_rf.py", line 41, in **init**
    self.dat = extract_pkt_data(self.raw_dat)
  File "/root/insteon/insteonrf/insteonrf/parse_rf.py", line 169, in extract_pkt_data
    if len(dm) < 13 :
UnboundLocalError: local variable 'dm' referenced before assignment
Traceback (most recent call last):
  File "./rf_reciv.py", line 111, in <module>
    print s
IOError: [Errno 32] Broken pipe

**Comment by petiepooo** [comment]
Fixed in df1c23d.  Issue can be closed?
